{% set name = "jupyterhub-systemdspawner" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8d614f19d89564321fe55d80ecd134a0e2bf276274d45861495c9bb5a80add28

build:
  number: 0
  skip: true  # [osx or win or py2k]
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python
  run:
    - jupyterhub >=0.9
    - python
    - tornado >=5.0

test:
  imports:
    - systemdspawner

about:
  home: https://github.com/jupyterhub/systemdspawner
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: JupyterHub Spawner using systemd for resource isolation
  description: |
    If you want to use Linux Containers (Docker, rkt, etc) for isolation and
    security benefits, but don't want the headache and complexity of container
    image management, then you should use the SystemdSpawner.

    With the systemdspawner, you get to use the familiar, traditional system
    administration tools, whether you love or meh them, without having to learn
    an extra layer of container related tooling.
  doc_url: https://github.com/jupyterhub/systemdspawner
  dev_url: https://github.com/jupyterhub/systemdspawner

extra:
  recipe-maintainers:
    - mwcraig
