{% set name = "jupyterhub-systemdspawner" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b6e2d981657aa5d3794abb89b1650d056524158a3d0f0f706007cae9b6dbeb2b

build:
  number: 4
  skip: true  # [osx or win or py2k]
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - jupyterhub >=0.9
    - python
    - tornado >=5.0

test:
  imports:
    - systemdspawner

about:
  home: https://github.com/jupyterhub/systemdspawner
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: JupyterHub Spawner using systemd for resource isolation
  description: |
    If you want to use Linux Containers (Docker, rkt, etc) for isolation and
    security benefits, but don't want the headache and complexity of container
    image management, then you should use the SystemdSpawner.

    With the systemdspawner, you get to use the familiar, traditional system
    administration tools, whether you love or meh them, without having to learn
    an extra layer of container related tooling.
  doc_url: https://github.com/jupyterhub/systemdspawner
  dev_url: https://github.com/jupyterhub/systemdspawner

extra:
  recipe-maintainers:
    - mwcraig
