travis:
  secure:
    BINSTAR_TOKEN: JmYIxbUPs1R0Yaf9MOOLz8OgAVXB/Fk8BPfYaJltdErrv677eqae/x0pl9QuP+OXQwgP4khwcegI/cQI9cS2fw0n9rcKwHkc0U81mnLzTZj2OtrDNF8x9tgoknxNd1inaGqssLoYt6yKULWulOp+EWURAFGKvr26N9QaH065UN7edzSXju72CM8azQUlcflF6sOExjRDc99BWIMPWtkb8sa8vw9wg4vapTPbu3mXrvUgZiZWitzyeD520yyDtJTvK6E1+rzVXcQ5hNSr+kHRAbguN3h+nqa1ANyVf7o8tfjYrw8W35FAKZoDdtd99o3qd+rNeoipQ78XEQoseLL57uXIj57IJT1EDgq8PK1Ui+e4t5vcurPT5TDwgaP/0a6DY29c3CWBZD7dSW3GqCi6NHn2wQjDDt4tFAM/ZtFhd3HXmnb0/79RE3bxsnF+pSH7FLY+YeSPA5ogB4dChjo97XTGLVX7/hTmhi65VUnH6Nr3OX6/XPpvWrnbZ+ftYRXYx/dTa8oGrqh+YjyFVvwYTpLU0KhnecqoJ9XS1wPGWwJ6VyqiyYb0tQZzvg7xfPBEIeArI/1+lLQoUISzYjpI6HYshJJ7dBtKB/p+NCtzUV6+cIkW44PqFdAORC/4uuoslnQ9baYl/sCbw40q7NR1l4SakPREtDK5RuANkpr+kek=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
