travis:
  secure:
    BINSTAR_TOKEN: vO2XUjGWjMVHMFXB2iLRLp2Wtty/wmc9t1B1DVoWywO6czSpNDzN2D9HA/rSOo/FF5PSij/rKl8Bk04mY3sAx9jMQcEOKwbh+yP6tJFppSrZMMnriDXzsklF6JqBwO8aKO2kXcrdzQbCdrwIcnPYyHAImyARh29plviJPSuKZ86eZZxHO4Wrud9S7ZOeIYtMAokMGjg5Oxk3BeA1EOevkvaS8+3tAb8lDdiUfTmPK3jkRSzk1zv1ExTE7RjkTQsTTT6PItrb6LWxQiGCHB3GLEe4Gg3uPiXkAvLrEolWgYZ6teKDpGupbHmqU1fC12X/8YPqAdIqicub2kv+Vn4nl2ZvEQ0I1yqdzIr2AON3XZxTu6Z6qCVnDlQ1pkaPW4LSkRm8/NTVozbAv04NzcX+Q1JwJvyNWskuvRcF+HW+H8/xXhUWrcOe+GQnHg+Dlp6w7Tud+MGQdJEvc7Qj5/zS2K6Vq1Ua08/ShRRJdFE5KjnFnjRTxhbrfF4NPVGziAAc45k0u4YU73BnwjLpsEwmfjJS7G/Qpd1x3aG03Py0zqD5LQigh/VmX5/TANA3701+IJJWErms3AkUtokkv+NyL5+8oXOe82arO0nA5V/y+55lEud7UBjkHcVsTpPUrLAP/s29dM+AdOtZh00CXgVPve8kfO7R+kGX1TEAoRA8X4E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
